global:
    server_ip: 127.0.0.1

backend_app:
    name: gateway
    version: 1.0.0
    base:
        start_timeout_sec: 30
        stop_timeout_sec: 15
        is_prod: false
        use_fx_logger: true
        use_logger: true
        log_sql_queries: true
        log_http: true
    http:
        port: 8080
        prefix: "api"
        under_proxy: false
        stop_timeout_sec: 3

auth:
    jwt_access_secret:

grpc:
    auth:
        addr: 127.0.0.1:50051
        retries_count: 5
        timeout: 60s
    ledger:
        addr: 127.0.0.1:50052
        retries_count: 5
        timeout: 60s
